//=== Deleting drawings

//@version=4
study("Last Bar Close 1", overlay=true)

c = close >= open ? color.lime : color.red
l = label.new(bar_index, na,
  text=tostring(close), color=c,
  style=label.style_label_down, yloc=yloc.abovebar)

label.delete(l[1])

//@version=4
study("Last Bar Close 2", overlay=true)

var label l = na
label.delete(l)
c = close >= open ? color.lime : color.red
l := label.new(bar_index, na,
  text=tostring(close), color=c,
  style=label.style_label_down, yloc=yloc.abovebar)

//@version=4
study("Last Bar Close 3", overlay=true)

var label l = label.new(bar_index, na,
  style=label.style_label_down, yloc=yloc.abovebar)

c = close >= open ? color.lime : color.red
label.set_color(l, c)
label.set_text(l, tostring(close))
label.set_x(l, bar_index)
