//=== Conditional coloring

//@version=4
study("Conditional colors", "", true)
int   i_length   = input(20, "Length", minval = 2)
color i_c_maBull = input(color.green, "Bull")
color i_c_maBear = input(color.maroon, "Bear")
float ma = sma(close, i_length)
// Define our states.
bool maRising  = rising(ma, 1)
// Build our color.
color c_ma = maRising ? i_c_maBull : i_c_maBear
plot(ma, "MA", c_ma, 2)
