// Example: a TradingView indicator with session inputs

//@version=5
indicator(title='Time ranges', overlay=true)

// Create the inputs
euSession = input.session(title='EU session', defval='0800-1530', confirm=true)
usSession = input.session(title='EU+US session', defval='1530-2200')
transparency = input.int(title='Transparency', defval=50, minval=0, maxval=100)

// The BarInSession function returns true when
// the current bar is inside the session parameter
BarInSession(sess) =>
    time(timeframe.period, sess) != 0

// Set the colour variables for the ranges
euColour = #6495ED  // Cornflower blue
usColour = #98FB98  // Pale green

// Determine the chart's background colour
BarInSession__1 = BarInSession(usSession)
chartColour = BarInSession(euSession) ? euColour : BarInSession__1 ? usColour : na

// Set the background colour
bgcolor(color=chartColour, transp=transparency)
