//=== Custom OHLC bars and candles

//@version=4
study("Example 1")
plotbar(open, high, low, close)

//@version=4
study("Example 2")
palette = close >= open ? color.lime : color.red
plotbar(open, high, low, close, color=palette)

//@version=4
study("Example 3")
c = close > open ? na : close
plotcandle(open, high, low, c)

//@version=4
study("Example 4")
len = input(9)
smooth(x) =>
    sma(x, len)
o = smooth(open)
h = smooth(high)
l = smooth(low)
c = smooth(close)
plotcandle(o, h, l, c)

// NOTE: add this script on intraday chart
//@version=4
study("Example 5")
higherRes = input("D", type=input.resolution)
is_newbar(res) =>
    t = time(res)
    not na(t) and (na(t[1]) or t > t[1])
o = security(syminfo.tickerid, higherRes, open)
h = security(syminfo.tickerid, higherRes, high)
l = security(syminfo.tickerid, higherRes, low)
c = security(syminfo.tickerid, higherRes, close)
plotbar(is_newbar(higherRes) ? o : na, h, l, c, color=c >= o ? color.lime : color.red)
