// Source: https://kodify.net/tradingview/orders/exits-always-fifo/
// Why are my TradingView exit orders always first in, first out?

//=== Problem: exit from specific entry trade doesn't work

// Exit from the second entry first
if (firstExit)
    strategy.close(id="EL 2")

//=== Solution: use close_entries_rule + exit from specific entries

// Set the close_entries_rule argument of the strategy() function to "ANY".
// Use order functions to exit from specific entries:

//=== Example strategy: override TradingView's default FIFO exits

//@version=4
strategy(title="Exit from specific entries", overlay=true,
     pyramiding=2, close_entries_rule="ANY")

// Determine trading conditions
newDay = (dayofmonth != dayofmonth[1])

firstEntry  = newDay and (dayofweek == dayofweek.monday)
secondEntry = newDay and (dayofweek == dayofweek.tuesday)

firstExit  = newDay and (dayofweek == dayofweek.thursday)
secondExit = newDay and (dayofweek == dayofweek.friday)

// Submit entry orders
if (firstEntry)
    strategy.entry(id="EL 1", long=true)

if (secondEntry)
    strategy.entry(id="EL 2", long=true)

// Generate exit orders
if (firstExit)
    strategy.close(id="EL 2")

if (secondExit)
    strategy.close(id="EL 1")

//=== Summary
