//=== heikinashi function

//@version=4
study("Example 5", overlay=true)
ha_t = heikinashi(syminfo.tickerid)
ha_low = security(ha_t, timeframe.period, low)
plot(ha_low)

//@version=4
study("Example 6", overlay=true)
t = tickerid(syminfo.prefix, syminfo.ticker, session.regular)
ha_t = heikinashi(t)
ha_low = security(ha_t, timeframe.period, low, gaps=barmerge.gaps_on)
plot(ha_low, style=plot.style_linebr)

//@version=4
study("Example 6.1")
ha_t = heikinashi(syminfo.tickerid)
ha_open = security(ha_t, timeframe.period, open)
ha_high = security(ha_t, timeframe.period, high)
ha_low = security(ha_t, timeframe.period, low)
ha_close = security(ha_t, timeframe.period, close)
palette = ha_close >= ha_open ? color.green : color.red
plotcandle(ha_open, ha_high, ha_low, ha_close, color=palette)
