a = open + high + low + close

a = open +
      high +
          low +
             close

plot(correlation(src, ovr, length),
   color=color.purple,
   style=plot.style_area,
   transp=40)

updown(s) =>
    isEqual = s == s[1]
    isGrowing = s > s[1]
    ud = isEqual ?
           0 :
           isGrowing ?
               (nz(ud[1]) <= 0 ?
                     1 :
                   nz(ud[1])+1) :
               (nz(ud[1]) >= 0 ?
                   -1 :
                   nz(ud[1])-1)

// Do not use comments with line wrapping. The following code does NOT compile:

//@version=4
study("My Script")
c = open > close ? color.red :
  high > high[1] ? color.lime : // a comment
  low < low[1] ? color.blue : color.black
bgcolor(c)
